### ISSUE TITLE
Problems about Experiments 

### ISSUE THREAD

**Issue by xlzhou01** [JonathanDZ/TF-FaSNet#1]
Hello author, when I read the experimental part of your paper, I didn’t quite understand your Speaker Angle in Table 1. How is it determined, what does it mean specifically, for example, is it compared to the angle of each microphone? (I don’t quite understand).

**Comment by JonathanDZ** [comment]
Apologies for any confusion. Regrettably, due to space constraints, we were unable to provide a comprehensive description of the experimental setup. To ascertain the speaker angle, you must initially sample the center of the microphone array. Following this, position two speakers in the room (referred to as speaker A and speaker B). In such a case, the speaker angle is defined as the angle between the line connecting speaker A to the array center and the line connecting speaker B to the array center. If you need further elaboration, please consult the following paper: "End-to-end Microphone Permutation and Number Invariant Multi-channel Speech Separation." I hope this clarifies your query.

**Comment by xlzhou01** [comment]
Thank you so much
